### ISSUE TITLE
HTTP Post Exception! Retrying.....('Connection aborted.', error(32, 'Broken pipe'))

### ISSUE THREAD

**Issue by gyoho** [jepcastelein/marketo-rest-python#15]
Executing the following command throws broken pipe error:

```
mc.execute(method='get_multiple_leads_by_filter_type', filterType='id', filterValues=updated_leadIds, fields=property_list, batchSize=300)

- updated_leadIds = list of ids (more than 10,000)
- fields = all properties in Lead object

```

This creates many batches. Even tough the 1st execution succeeds, executing 2nd execution with the `nextPageToken` will throws:

HTTP Post Exception! Retrying.....('Connection aborted.', error(32, 'Broken pipe'))

**Comment by jepcastelein** [comment]
@mahimasetia it usually occurs when you're trying to do something that the Marketo API does not support. In case of the example above, 'get_multiple_leads_by_filter_type' only accepts 100 Lead IDs as filterValues.

**Comment by mahimasetia** [comment]
I am trying to 
for i in mc.execute(method = 'get_activity_types'):
    print(i['name'], i['id'])

**Comment by mahimasetia** [comment]
HTTP Get Exception! Retrying.....
HTTP Get Exception! Retrying.....
HTTP Get Exception! Retrying.....
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-6-9e56ef6f1c47> in <module>()
----> 1 mc.execute(method='get_multiple_leads_by_filter_type', filterType='id',filterValues=100)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\marketorestpython\client.py in execute(self, method, *args, **kargs)
    260                     'get_activities_export_job_file': self.get_activities_export_job_file
    261                 }
--> 262                 result = method_map[method](*args, **kargs)
    263             except MarketoException as e:
    264                 '''

~\AppData\Local\Continuum\anaconda3\lib\site-packages\marketorestpython\client.py in get_multiple_leads_by_filter_type(self, filterType, filterValues, fields, batchSize)
    315 
    316     def get_multiple_leads_by_filter_type(self, filterType, filterValues, fields=None, batchSize=None):
--> 317         self.authenticate()
    318         if filterType is None:
    319             raise ValueError(

~\AppData\Local\Continuum\anaconda3\lib\site-packages\marketorestpython\client.py in authenticate(self)
    285         data = self._api_call('get', self.host + "/identity/oauth/token", args)
    286         if data is None:
--> 287             raise Exception("Empty Response")
    288         if 'error' in data:
    289             if data['error'] in ['unauthorized', 'invalid_client']:

Exception: Empty Response
