### ISSUE TITLE
authenticate() assumes valid credentials

### ISSUE THREAD

**Issue by mmoravcik** [jepcastelein/marketo-rest-python#2]
If you don't provide a valid credentials, you'll get
```
    ipdb> mc.authenticate()
    *** KeyError: 'access_token'
```

The code in question: https://github.com/jepcastelein/marketo-rest-python/blob/master/marketorestpython/client.py#L205

**Comment by jepcastelein** [comment]
Good point, in the new version 0.3 I am passing through the error message from the Marketo API, which is either 'Bad Client Credentials' or 'No client with requested id'. Let me know if that works for you.
