### ISSUE TITLE
offset not supported

### ISSUE THREAD

**Issue by Spince** [jepcastelein/marketo-rest-python#20]
Is offset not supported? I don't see it documented and would like to use it for emails. I think I see the functionality has been implemented for Folders and Programs where they both loop through all results until everything is returned (assuming that's done utilizing the offset). Is this possible with emails? 

From the Marketo documentation:
Browsing through assets will always permit two query parameters:

offset – An integer offset to return results from.
maxReturn – Limits the number of records returned.  Defaults to 20 if unset, and has a maximum of 200.
http://developers.marketo.com/rest-api/assets/

**Comment by jepcastelein** [comment]
it will automatically download all emails, so it uses offset in the background. It is not possible to pass in offset yourself. Here's the source https://github.com/jepcastelein/marketo-rest-python/blob/b352c51c5987cc324137b3a3cc1f5d9302b0841a/marketorestpython/client.py#L1920

**Comment by jepcastelein** [comment]
there is a new function/generator `get_emails_yield` that supports the offset parameter. Not yet documented, but easy to find in the source of client.py (there are also new generators for program, email template, landing page template, landing pages, files, snippets and forms, all include offset)
