### ISSUE TITLE
0.3.8 only works with Python>=3.6, does not work with Python2

### ISSUE THREAD

**Issue by rezende** [jepcastelein/marketo-rest-python#25]
Version 0.3.8 uses f-strings:

https://github.com/jepcastelein/marketo-rest-python/blob/b352c51c5987cc324137b3a3cc1f5d9302b0841a/marketorestpython/client.py#L4824

Was this intentional? It breaks support for Python 2.7.

If it was intentional, it's appreciated to add a warning that this version only works with Python>= 3.6

Thanks!

**Comment by jepcastelein** [comment]
not intentional, it was part of a recent pull request and I missed it in the code review. I don't have time to fix and test it right now, but if you want to fix it and open pull request, I will merge it. Or use the previous version for now:  `pip install marketorestpython==0.3.7`
