### ISSUE TITLE
how to get all opportunities?

### ISSUE THREAD

**Issue by tejasmanohar** [jepcastelein/marketo-rest-python#4]
continuation of https://github.com/jepcastelein/marketo-rest-python/pull/3

**Comment by jepcastelein** [comment]
with Describe Opportunity you get all searchable fields, which for my Marketo instance are : 
'externalOpportunityId'], ['marketoGUID'],['externalCompanyId'],	['externalSalesPersonId'],	['additionalInformation'],	['customOpportunityId'],	['natServiceCode'],	['oppStatus'],	['opportunityID'],	['organizationID'],	['serviceDesc'],	['serviceLineDesc'],	['svcProposition']

They do require exact matches, so it assumes that the system of record for Opportunities is outside of Marketo and that you get the IDs from there, then pass them into the API calls. There is no specific API function that gives you all Opportunities.

**Comment by tejasmanohar** [comment]
interesting , i suppose it's possible via the SOAP API though?

http://developers.marketo.com/documentation/soap/getmobjects/
http://developers.marketo.com/documentation/soap/listmobjects/

**Comment by jepcastelein** [comment]
Yes, generally I would not recommend using SOAP, but this specific feature is one of the few things that is possible with SOAP but not yet with REST.

**Comment by tejasmanohar** [comment]
Gotcha
