### ISSUE TITLE
add exponential backoff and jitter

### ISSUE THREAD

**Issue by rayrrr** [jepcastelein/marketo-rest-python#41]
In http://developers.marketo.com/rest-api/error-codes one of the error codes states: 

502 | Bad Gateway | The remote server returned an error. Likely a timeout. The request should be retried with exponential backoff.

In fact, [exponential backoff](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter) is a good error handling strategy in many cases. https://github.com/litl/backoff already provides the feature; would you be willing to introduce a dependency on that package here so we could use it to decorate the `execute` method?

**Comment by jepcastelein** [comment]
exponential would be nice, but not sure if necessary. The library already has retry for other error message: 
https://github.com/jepcastelein/marketo-rest-python/blob/master/marketorestpython/helper/http_lib.py#L42

It would be really simple to add 502 to that. 

But I agree that exponential would be nice and the `backoff` package seems solid.

**Comment by rayrrr** [comment]
@jepcastelein thanks! I will be submitting a PR with `backoff` added soon. In the meantime, since I will be doing substantial work in `http_lib.py` I made a separate PR that is purely formatting in that file first: https://github.com/jepcastelein/marketo-rest-python/pull/44 I'd like to work against that version if possible.

**Comment by rayrrr** [comment]
On second thought, don't worry about that. I closed #44 because of #35 being open and having lots of changes on the same lines.

**Comment by rayrrr** [comment]
@jepcastelein I'm back from a break and working on this now. Are you willing to merge #35 to master? It would make my work easier.

**Comment by rayrrr** [comment]
PR #46 is ready for review. The changes removed most of if not all the too-long-for-PEP8 lines in `http_lib.py` anyways.

**Comment by jepcastelein** [comment]
Thanks, I just published version 0.4.1 including backoff support. I made the max_retry_time configurable, which was not as straightforward as I thought it would be. If you have any ideas on how to improve, please let me know.

**Comment by rayrrr** [comment]
Great news, thanks. I will give the matter of configuration some thought.
