### ISSUE TITLE
get_lead_activities incredibly slow

### ISSUE THREAD

**Issue by alycege** [jepcastelein/marketo-rest-python#42]
Been trying to get lead activities for a specific user with the delta between sinceDatetime and untilDatetime of less than 1 week. I know the results it's supposed to return because I went in and checked in Marketo, but it's taken 2+ hours so far. Not sure if this is a library issue or a Marketo issue.

**Comment by mahimasetia** [comment]
better to try for a day a time

**Comment by alycege** [comment]
Still very slow for 1 user & 1 day

**Comment by jepcastelein** [comment]
the API is not very efficient to retrieve few Activities, such as only 1 activity type for a single Lead over a longer period of time. It is scanning all activities in blocks, for each block it returns a response, even if no activities found for your Lead & activity type. Then the library passing in a new nextPageToken to scan the next block, and so forth. So yes, it can take a long time if there are a lot of activities in the Marketo instance, but you're only requesting very few.
