### ISSUE TITLE
marketo variables

### ISSUE THREAD

**Issue by mahimasetia** [jepcastelein/marketo-rest-python#43]
I need marketo variables like Opportunity cost, opportunity topic etc. 
below is the link to rest api 
http://developers.marketo.com/rest-api/lead-database/opportunity-roles/

how can i pull them using the python API.

**Comment by jepcastelein** [comment]
from the readme: 
https://github.com/jepcastelein/marketo-rest-python#get-opportunities
https://github.com/jepcastelein/marketo-rest-python#get-opportunity-roles

**Comment by jepcastelein** [comment]
From the link you shared: _"Opportunity Role APIs are only exposed for subscriptions which do not have a native CRM sync enabled."_ 
Could that be the problem?

**Comment by mahimasetia** [comment]
Not very sure. How can I check CRM sync for my account? Also, is there any other way to pull opportunity cost?

**Comment by jepcastelein** [comment]
Check the Admin section in the Marketo UI
If you do have native sync (SFDC or Microsoft CRM), you need to connect to your CRM system's API, which is the system of record for Opportunities

**Comment by jepcastelein** [comment]
also, https://docs.marketo.com/display/public/DOCS/Welcome+to+Marketo+Docs is a great resource
