### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by ataki** [jepcastelein/marketo-rest-python#49]
Hi @jepcastelein! Thanks for making this project - it's come in handy for us.

Recently, we've been moving our tech stack to Python3, and realized this project may not yet support 3, which blocks us from upgrading. I was wondering whether you could help clarify whether:

1. this package in fact does support Python3
2. if not, is there a path forward for support?

Thanks!

**Comment by jepcastelein** [comment]
Yes, it supports Python 3.
