### ISSUE TITLE
Unable to fetch Data using Date column from Marketo

### ISSUE THREAD

**Issue by jagadishsethy** [jepcastelein/marketo-rest-python#53]
Hi Jepcastelein,

1) I m unable to fetch the lead data using date field i.e. "createdAt" from Marketo. Below is the code using:
lead = mc.execute(method='get_multiple_leads_by_filter_type', filterType='createdAt', filterValues='2018-01-01')

It is throwing error as:
{'message': "Lookup field 'createdAt' not supported", 'code': '1011'}

2) How to fetch lead data for range of date?

**Comment by jepcastelein** [comment]
See https://www.linkedin.com/pulse/read-before-using-marketos-weird-rest-api-jep-castelein/, paragraph "Weird Limitations, Gotchas and Tips", third bullet
