### ISSUE TITLE
No exit condition for get_lead_changes

### ISSUE THREAD

**Issue by shartrich** [jepcastelein/marketo-rest-python#55]
This is an awesome repo that really makes the most out of Marketo's dreadful api, but I have encountered one debilitating bug. 

When calling MarketoClient.get_lead_changes with both a valid untilDate, the service continues to make api calls to Marketo even after the MarketoClient.process_lead_activity_until_datetime identifies that latest_until_date exceeds the untilDatetime. Once this occurs, the MarketoClient.get_lead_changes should exit and return the current result_list.

Instead, the while loop continues until ALL leadchanges callouts are finished which for older sinceDatetime can be a LONG time.

https://github.com/jepcastelein/marketo-rest-python/blob/83d57d74453a4733cc7ca16522d0b110a6830d1a/marketorestpython/client.py#L1152-L1155

**Comment by jepcastelein** [comment]
Thanks for reporting this. This should be fixed in 0.5.4.
