### ISSUE TITLE
Method browse_programs lacks the offset parameter

### ISSUE THREAD

**Issue by tiagoadm** [jepcastelein/marketo-rest-python#71]
While the REST API supports it, **browse_programs** current implementation is missing the offset parameter, which means we are limited to a list of max 200 programs. 

If I want to do an initial load and have more than 200 programs, this method won't do the job, and I will have to use HTTP calls instead.

**Comment by jepcastelein** [comment]
Hi @tiagoadm it'll loop for you and return all Programs at once. If you'd like to get them 200 at a time, use `get_programs_yield` which is not in the README but it's a generator so you can iterate over it.
