### ISSUE TITLE
Delete in CRM?

### ISSUE THREAD

**Issue by joefusaro** [jepcastelein/marketo-rest-python#72]
Hi, when using the method `delete_lead` is there a way to pass in a parameter to delete the Lead in the CRM as well? 

I don't see it in Marketo's docs, and I don't see in the code anywhere.

**Comment by jepcastelein** [comment]
Hi @joefusaro! No, I don't think there is such an option in the API. If it's not in the API reference on the Marketo Developer website, then it generally doesn't exist.
