### ISSUE TITLE
Add support for `clone_smart_campaign`?

### ISSUE THREAD

**Issue by jonathanlaniado** [jepcastelein/marketo-rest-python#74]
Love the work you've done here. Any reason this one isn't implemented? This one would be vital for us to incorporate, thank you.

Endpoint documentation: https://developers.marketo.com/rest-api/endpoint-reference/asset-endpoint-reference/#!/Smart_Campaigns/cloneSmartCampaignUsingPOST

**Comment by jepcastelein** [comment]
they weren't there because they were added to the Marketo API later. But it's your lucky day, I had a spare hour and added them

**Comment by jonathanlaniado** [comment]
Huge, thank you Jep! 🙏
