### ISSUE TITLE
Publish new versions to pypi?

### ISSUE THREAD

**Issue by jakedt** [jepcastelein/marketo-rest-python#8]
It looks like the latest version on pypi is 0.2.0.

**Comment by jepcastelein** [comment]
I see 0.3.3 at https://pypi.python.org/pypi/marketorestpython and download link here: https://pypi.python.org/packages/49/82/3591d9d0af2d52691fa72c39117c7f2880f79d5abeb2938a09c504fb0e2e/marketorestpython-0.3.3.zip#md5=fc131f11b19ea4137db8d349ce760fe7
